# Generated by Django 4.0.6 on 2022-07-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='user_id',
        ),
    ]
