# Generated by Django 4.0.6 on 2022-07-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_listing_id_watchlist_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='comment_date'),
        ),
    ]
