# Generated by Django 4.0.6 on 2022-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.SlugField(max_length=150),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
